src/specs/api.yaml
Added auditLevel
Added auditLevel
- [ATB-1089](https://govukverify.atlassian.net/browse/ATB-1089)
[ATB-1089]: https://govukverify.atlassian.net/browse/ATB-1089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1089: added auditLevel

src/specs/api.yaml
Updated from VERIFIED to REVERIFIED in the description enaum
Requested  -see [here](https://gds.slack.com/archives/C04N83W7V2N/p1697553976755339?thread_ts=1696926457.395069&cid=C04N83W7V2N)
- [ATB-1089](https://govukverify.atlassian.net/browse/ATB-1089)
[ATB-1089]: https://govukverify.atlassian.net/browse/ATB-1089?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1089: Updated from VERIFIED to REVERIFIED

src/infra/alarm/samconfig.toml, src/infra/alarm/template.yaml, src/infra/main/samconfig.toml, src/infra/main/template.yaml
[ATB-1074]
- Adding the TxMa Ingress Queue and DLQ
- Adding TxMa Alarms
- To trigger the interventions-processor lambda.
Templates deployed:
[ATB-1074]: https://govukverify.atlassian.net/browse/ATB-1074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1074 | TxMA Ingress Queue and Alarms

src/infra/main/template.yaml
Added codesigning config to `AccountDeletionProcessorFunction` resource 
this property needs to be present for deploying with secure pipeline to succeed 
deployment through GH workflow succeeded
=> Quick fix for DeletionProcessor Lambda 

.github/workflows/manual-publish-alarm-to-dev.yaml, .github/workflows/merge-alarm-to-main.yaml, .github/workflows/test-workflow.yaml, .github/workflows/validate-alarm-sam-template.yaml, .github/workflows/validate-main-sam-template.yaml, src/infra/alarm/template.yaml, src/infra/main/template.yaml, stack-orchestration/build_pipelines.sh, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-dev-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-core-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-main-pipeline/parameters.json, stack-orchestration/development_pipelines.sh, stack-orchestration/staging_pipelines.sh
ATB -1125: Establish Alarm template workflow
ATB-1126: Establish core, main, and alarm pipeline in staging along with alarm pipeline in dev and build
Established secure pipelines in build, dev, and staging environments as follows: 
Dev: ais-alarm-pipeline 
Build: ais-alarm-pipeline
Staging: ais-core-pipeline , ais-main-pipeline , ais-alarm-pipeline
Created Github workflows for our Alarm template - manual-publish-alarm-to-dev.yaml + merge-alarm-to-main.yaml
To provide pipelines for the Alarm stack in dev, build and staging and a workflow for our Alarm template. 
- [ATB-1126](https://govukverify.atlassian.net/browse/ATB-1126)
[ATB-1126]: https://govukverify.atlassian.net/browse/ATB-1126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB 1125 + ATB 1126 | Establish pipelines in dev, build and staging for alarms and create GitHub workflows for Alarm template

.github/workflows/manual-publish-alarm-to-dev.yaml, .github/workflows/manual-publish-core-to-dev.yaml, .github/workflows/manual-publish-main-to-dev.yaml, .github/workflows/merge-alarm-to-main.yaml, .github/workflows/merge-core-to-main.yaml, .github/workflows/merge-main-to-main.yaml
Updated the action in our core, main, and alarm workflows to point to govuk-one-login instead of the previous AlphaGov 
We will no longer be using AlphaGov actions after the migration, therefore replacing. 
- [ATB-1134](https://govukverify.atlassian.net/browse/ATB-1134)
[ATB-1134]: https://govukverify.atlassian.net/browse/ATB-1134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1134 | Update Upload Action in our core, main, and alarm workflows to point to govuk-one-login

.github/workflows/acceptance-checks.yaml, .gitignore, README.md, sonar-project.properties
Added sonarcloud config
Enable SAST
- [ATB-991](https://govukverify.atlassian.net/browse/ATB-991)
[ATB-991]: https://govukverify.atlassian.net/browse/ATB-991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-991: Added SonarCloud config

src/infra/main/template.yaml
AddingCodeSigningConfigArn property into our Status Retriever Function 
Missing AddingCodeSigningConfigArn  
=> Deployment Fix

src/infra/main/template.yaml
ATB 1091: Get VPC IDs or Account IDs for Private API resource policy
Updated all Staging VPC IDs to vpc-02e4eb3b0cffc08b0 to allow access from di-performance-test-prod (#330163506186*) 
Added Orchestration and Authentication VPC IDs (Shared) in Integration and Production Mappings. 
To allow our Private ApiGateway to work with Auth, Orch and OLH (GET method) and to facilitate performance testing in staging. 
- [ATB-1091](https://govukverify.atlassian.net/browse/ATB-1091)
[ATB-1091]: https://govukverify.atlassian.net/browse/ATB-1091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1091 | Attained VPC IDs for Orchestration, Authentication and One Login Home 

package.json, yarn.lock
Updated dependencies to the latest version, except for node.
To ensure we're keeping the repo up to date
- [ATB-1175](https://govukverify.atlassian.net/browse/ATB-1175)
N/A
[ATB-1175]: https://govukverify.atlassian.net/browse/ATB-1175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1175 Update dependencies

src/infra/core/template.yaml
ATB-1177:  Add a AWS KMS key for encrypting the data stored in our DynamoDB table
Add a KMS key for encrypting the data stored in our DynamoDB table 
Enable Server-Side Encryption 
We need a KMS Key on our DynamoDB table - CKV_AWS_119
- [ATB-1177](https://govukverify.atlassian.net/browse/ATB-1177)
[ATB-1177]: https://govukverify.atlassian.net/browse/ATB-1177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1177 |  Add a AWS KMS key for encrypting the data stored in our DynamoDB table

src/infra/core/template.yaml
ATB-1183: Enable Point In Time Recovery on our Account Status Table
Added property `PointInTimeRecoverySpecification` to our DynamoDB resource. 
Enabling PITR will protect our DB from accidental deletes/ writes and allows us to restore the table to any point in time provided it's within the 35 days range. 
- [ATB-1183](https://govukverify.atlassian.net/browse/ATB-1183)
[ATB-1183]: https://govukverify.atlassian.net/browse/ATB-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1183 | Enable Point In Time Recovery on our Account Status Table

src/infra/core/template.yaml, src/infra/main/template.yaml
- [ATB-1182 | Update lambda permissions to update DynamoDB](https://govukverify.atlassian.net/browse/ATB-1182)
Updated permissions for the state updater, deleter and retriever lambdas.
The status table recently had encryption added to the table which meant the lambdas did not have the right permissions to update and read from it.
Tested each lambda in the aws console to ensure functionality of each is working
=> ATB 1182 - updated lambda permissions to access dynamo db table

stack-orchestration/configuration/di-account-interventions-integration-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-integration-admin/ais-core-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-integration-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-production-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-production-admin/ais-core-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-production-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-core-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-core-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-main-pipeline/parameters.json
ATB-1168 : Switchover BuildNotificationStackName to ais-infra-alerting in all secure pipeline stacks
Updated value present under  BuildNotificationStackName in all current secure pipelines in `build`,  `staging`, `integration` and `production`  envs and replaced it with ` ais-infra-alerting ` instead. 
This change is taking place because we have now created `ais-infra-alerting` stack, and our deployment pipelines can be configured to send build notifications to our slack channel. 
- [ATB-1168](https://govukverify.atlassian.net/browse/ATB-1168)
[ATB-1168]: https://govukverify.atlassian.net/browse/ATB-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1168 | Switchover BuildNotificationStackName to ais-infra-alerting in all secure pipeline stacks

src/infra/alarm/template.yaml
ATB-1194: Reconfigure AIS Alarms template to point to our new ais-infra-alerting SNS Topics
AIS Alarms template parameters  AlertingSNSLowAlertNotificationTopicARN & AlertingSNSHighAlertNotificationTopicARN are now referencing the new `ais-infra-alerting` template. 
This change occurred because we will no longer be using our `infra-alerting` stack SNS Topics for AIS Alarms now that we have a new slack channel too. 
- [ATB-1194](https://govukverify.atlassian.net/browse/ATB-1194)
[ATB-1194]: https://govukverify.atlassian.net/browse/ATB-1194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1194 | Reconfigure AIS Alarms template to point to our new ais-infra-alerting SNS Topics

src/infra/core/template.yaml, src/services/dynamo-database-service.ts, src/services/test/dynamo-database-service.test.ts
[ATB-1139]
- Switch on TTL configurations on account status table
- To add TTL to the table for better tracking
- [ATB-1139](https://govukverify.atlassian.net/browse/ATB-1139)
TTL comes up as option:
[ATB-1139]: https://govukverify.atlassian.net/browse/ATB-1139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATB-1139]: https://govukverify.atlassian.net/browse/ATB-1139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1139 | Adding TTL to Core Template

src/handlers/interventions-processor-handler.ts, src/infra/alarm/template.yaml
Added alarms for interventions processor lambda.
- [ATB-1165](https://govukverify.atlassian.net/browse/ATB-1165)
[Doc1.docx](https://github.com/govuk-one-login/account-interventions-service/files/13416665/Doc1.docx)
[ATB-1165]: https://govukverify.atlassian.net/browse/ATB-1165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1165 Alarms for interventions processor lambda

src/handlers/status-retriever-handler.ts
- Using optional chain expression instead to fix SonarCloud code smell
- To fix code smell
- [ATB-1146](https://govukverify.atlassian.net/browse/ATB-1146)
- all the services still work
[ATB-1146]: https://govukverify.atlassian.net/browse/ATB-1146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1146 | Fixing code smell

src/data-types/schemas.ts, src/services/test/validate-event.test.ts
Added changes to the schema so that we align with https://github.com/govuk-one-login/txma-event-self-serve/blob/24c4b071e91d3d84390276cc93cadde0595880bb/config/consumer/sqs/accountsInterventionService.json#L16
- [ATB-1202](https://govukverify.atlassian.net/browse/ATB-1202)
[Doc1.docx](https://github.com/govuk-one-login/account-interventions-service/files/13459806/Doc1.docx)
[ATB-1202]: https://govukverify.atlassian.net/browse/ATB-1202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1202 Update JSON schemas for ingress TxMA messages

src/infra/alarm/template.yaml
ATB-1231:  First parameter change in ais-alarm template
Creating a parameter change in the` ais-alarm `template and then will be reverting it back to the previous name. 
After updating the parameter default to reference our` ais-infra-alerting` template, the change was not picked up in the alarms and still referencing infra-alerting SNS Topic instead. 
- [ATB-1231](https://govukverify.atlassian.net/browse/ATB-1231)
[ATB-1231]: https://govukverify.atlassian.net/browse/ATB-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1231 | First parameter change in ais-alarm template

src/infra/alarm/template.yaml
ATB-1232: Revert the ais-alarm template parameter back 
Reverting the ais-alarm template parameters back to  `AlertingSNSLowAlertNotificationTopicARN` & `AlertingSNSHighAlertNotificationTopicARN` 
After updating the parameter default to reference our ais-infra-alerting template, the change was not picked up in the alarms and still referencing infra-alerting SNS Topic instead so reverting the changes back from this PR - https://github.com/govuk-one-login/account-interventions-service/pull/91 
- [ATB-1232](https://govukverify.atlassian.net/browse/ATB-1232)
[ATB-1232]: https://govukverify.atlassian.net/browse/ATB-1232?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1232 | Revert the ais-alarm template parameter back 

src/infra/main/template.yaml
[ATB-1113](https://govukverify.atlassian.net/browse/ATB-1113)
Added role to the invoke private api lambda.
Pipelines require a lambda role to be created explictly.
[ATB-1113]: https://govukverify.atlassian.net/browse/ATB-1113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1113 Added role to invoke private api lambda

src/commons/history-string-builder.ts, src/commons/logger.ts, src/commons/metrics.ts, src/commons/tracer.ts, src/handlers/account-deletion-processor-handler.ts, src/handlers/interventions-processor-handler.ts, src/handlers/status-retriever-handler.ts, src/services/dynamo-database-service.ts, src/services/send-audit-events.ts
[ATB-1238](https://govukverify.atlassian.net/browse/ATB-1238)
reviewed and updated docstrings in our AIS codebase to ensure they are present and meet the required format
Improve code documentation
Passes linting checks:
[ATB-1238]: https://govukverify.atlassian.net/browse/ATB-1238?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1238:  Review and update DocStrings

feature-tests/run-tests.sh, feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature, feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts, feature-tests/utils/send-sqs-message.ts
Added new test scenarios to AIS Happy Path for all AIS Event Types
Added Happy Path Field Validation Test for AIS
New Test Scenarios have been added
To increase coverage of feature-tests
- [ATB-1207](https://govukverify.atlassian.net/browse/ATB-1207)
All new tests added passed:
[ATB-1207]: https://govukverify.atlassian.net/browse/ATB-1207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1207 - AIS: Update feature-tests with additional test scenarios (Happy Paths)

src/commons/test/build-partial-update-state-command.test.ts, src/commons/test/compile-schema.test.ts, src/commons/test/history-string-builder.test.ts, src/commons/test/metrics-logging.test.ts, src/commons/test/update-account-state-metrics.test.ts, src/data-types/interfaces.ts, src/data-types/schemas.ts, src/handlers/interventions-processor-handler.ts, src/handlers/tests/interventions-processor-lambda.test.ts, src/handlers/tests/status-retriever-handler.test.ts, src/infra/main/samconfig.toml, src/services/test/dynamo-database-service.test.ts, src/services/test/validate-event.test.ts, src/services/validate-event.ts
This PR merges changes to refactor the main method in the Interventions Processor lambda and ensures that we log error messages appropriately and clearly
- refactor processing method in intervention processor lambda handler
- moved event validation method to validate-event file
- remove/modified logging lines
Improve code redability
- [ATB-1141](https://govukverify.atlassian.net/browse/ATB-1141)
UTs passing and coverage maintained 
Changes deployed to AWS account and tested following scenarios:
- post valid message --> intervention is applied ✅ 
- post invalid intervention message --> validation fails, event not retried ✅ 
- post invalid password reset event --> validation fails, event not retried ✅ 
- post invalid id reset event --> validation fails, event is not retried ✅ 
- …
=> ATB-1141 | Refactoring

src/data-types/schemas.ts, src/specs/api.yaml
This ticket is to merge changes to the API spec so that all fields display correctly in the swagger view
Created schema for history object
Added some field to our schema to get rid of warning message when schema is compiled
Improve documentation of our api
- [ATB-1253](https://govukverify.atlassian.net/browse/ATB-1253)
API spec displays correctly in swagger now
UT run does not produce warning message anymore related to the schema
[ATB-1253]: https://govukverify.atlassian.net/browse/ATB-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1523 | API Spec Update

src/infra/main/template.yaml
Added log groups for each lambda
Added subscription filter to each log group in prod and int envs
- [ATB-1241](https://govukverify.atlassian.net/browse/ATB-1241)
- [ATB-1242](https://govukverify.atlassian.net/browse/ATB-1242)
[ATB-1241]: https://govukverify.atlassian.net/browse/ATB-1241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATB-1242]: https://govukverify.atlassian.net/browse/ATB-1242?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB 1241 & ATB 1242 Adding log groups to lambdas and subscriptions to CSLS

feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
Added longer wait between the SQS call to send the Intervention and the API gateway call to retrieve the Intervention state
Increased time delay between SQS message sending and Private AOI Gateway Method invoking
When the tests are first run on the pipelines in AWS. Cold starts can cause delays which means the first 1 or 2 tests will fail.
- [ATB-1271](https://govukverify.atlassian.net/browse/ATB-1271)
All tests passing locally in Dev
All tests passing in AWS piepline in Dev
[ATB-1271]: https://govukverify.atlassian.net/browse/ATB-1271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1271 - AIS: Update invoke-api-gateway-happy-path.step.ts to increase wait

src/infra/main/template.yaml
Small PR to fix deployment issue
Added string interpolation to a CSLS sub resource to point to the right log group
Deployment
=> Fix for failed deployment due to CSLS subscription

feature-tests/apiEndpoints/endpoints.ts, feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature, feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
Updated the feature file to use one single scenario outline for changing the AIS event to other AIS events
To Reuse of Step definitions
- [ATB-1376](https://govukverify.atlassian.net/browse/ATB-1376)
[ATB-1376]: https://govukverify.atlassian.net/browse/ATB-1376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1376: Updated the feature file to use one scenario

src/infra/main/template.yaml
fixed pipeline issues
broken builds
- [ATB-1378](https://govukverify.atlassian.net/browse/ATB-1378)
[ATB-1378]: https://govukverify.atlassian.net/browse/ATB-1378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1378: fixed pipeline issues

feature-tests/jest.config.ts, feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature, package.json
Add feature tests for pswResetRequired, idResetRequired, pswAndIdResetRequired and unblock
To increase the coverage
- [ATB-1357](https://govukverify.atlassian.net/browse/ATB-1357)
[ATB-1357]: https://govukverify.atlassian.net/browse/ATB-1357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1357: Added tests to increase the coverage

stack-orchestration/build_pipelines.sh, stack-orchestration/configuration/di-account-interventions-integration-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-integration-admin/ais-core-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-integration-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-production-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-production-admin/ais-core-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-production-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-core-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-dev-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-dev-admin/ais-core-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-dev-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-dev-admin/ais-test-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-alarm-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-core-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-main-pipeline/parameters.json, stack-orchestration/development_pipelines.sh, stack-orchestration/integration_pipelines.sh, stack-orchestration/production_pipelines.sh, stack-orchestration/staging_pipelines.sh
ATB-1408 | Update core/main/alarm pipeline stack orchestration configuration parameters
Updated Stack Orchestration configuration files to reflect what is currently present in AWS console as well as updated some parameters. 
- `SlackNotificationType` from `none` to `Failures` in `int` and `prod` configuration files. 
- Added Prod Account number to ParameterKey AllowedAccounts in `staging` for `ais-main-pipeline` , `ais-core-pipeline` and `ais-alarm-pipeline`. 
- Updated `ais-main-pipeline` with required parameter modifications for our Dynatrace Lambda Layer under the Parameter Keys `AdditionalCodeSigningVersionArns` and  `CustomKmsKeyArns`  which was already present in console for `dev`, `build` and `staging` only  , however, added as a parameter into configuration files for `int` and …
=> ATB-1408 | Update core/main/alarm pipeline stack orchestration configuration parameters

stack-orchestration/configuration/di-id-reuse-core-build-admin/tags.json
ATB-1415: Missing a tags.json file to in Stack Orchestration build configuration. 
Added a tags.json file to Stack Orchestration build configuration.
Required to for stack orchestration tool to run. 
- [ATB-1415](https://govukverify.atlassian.net/browse/ATB-1415)
[ATB-1415]: https://govukverify.atlassian.net/browse/ATB-1415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1415 | Missing a tags.json file to in Stack Orchestration build configuration

feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
updated history validation
following a change to validation, the history tests were failing
To resolve failing history tests
- [ATB-1422](https://govukverify.atlassian.net/browse/ATB-1422)
All tests passing in Dev locally: 
All tests passing in Dev on the Pipeline
[ATB-1422]: https://govukverify.atlassian.net/browse/ATB-1422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1422 - Feature-tests - Update invoke-api-gateway-happy-path.step.ts to resolving failing history tests

.github/workflows/manual-publish-feture-tests-to-dev.yaml, .github/workflows/merge-feature-tests-to-main.yaml
updated name for publish feature tests to dev workflow added merge feature-tests to main workflow
Updated the Publish feature-tests to Dev workflow
Added the Publish feature tests to main Workflow (Build ECR Test Image Push)
To enable test images to be pushed to the Build ECR Repo and feature-tests to be run on the AIS Main Pipeline
- [ATB-1377](https://govukverify.atlassian.net/browse/ATB-1377)
[ATB-1377]: https://govukverify.atlassian.net/browse/ATB-1377?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1377 - Feature Tests: Added Merge Feature-tests to main workflow

stack-orchestration/build_pipelines.sh, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-test-ecr/parameters.json
ATB-1428: Set up test ECR container and test pipeline in build
Set up ais-test-ecr stack 
Setting up the test image repository stack which create an ECR repository to run our tests. 
We have decided not to create a `ais-test-pipeline` stack and instead use the values from our `ais-main-pipelines` stack for `GitHubActionsRoleArn` instead as we will be adding the test action to the stack too so there would be no need for another `GitHubActionsRoleArn` from another pipeline and we can use the same one for testing 
- [ATB-1428](https://govukverify.atlassian.net/browse/ATB-1428)
[ATB-1428]: https://govukverify.atlassian.net/browse/ATB-1428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1428 | Set up test ECR container and test pipeline in build

stack-orchestration/configuration/di-account-interventions-integration-admin/vpc/parameters.json, stack-orchestration/configuration/di-account-interventions-production-admin/vpc/parameters.json, stack-orchestration/integration_bootstrap.sh, stack-orchestration/production_bootstrap.sh
ATB-1438: Deploy latest version of VPC and Update Stack Orchestration config
Updated VPC stack orchestration config and set DynatraceApiEnabled to Yes in the VPC Stack's parameters, to allow the Lambda function to call the Dynatrace API.
Keep Stack Orchestration up to date. 
- [ATB-1438](https://govukverify.atlassian.net/browse/ATB-1438)
[ATB-1438]: https://govukverify.atlassian.net/browse/ATB-1438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1438 | Deploy latest version of VPC and Update Stack Orchestration config

README.md, stack-orchestration/integration_bootstrap.sh, stack-orchestration/production_bootstrap.sh
ATB-1448: Update README with latest stack versions
ATB-1444: Update base CloudFormation stacks to latest versions
README version table and bootstrap scripts with new versions for AIS integration and Production. 
To keep consistent with what's in Console and Dev Platform updates 
- [ATB-1448](https://govukverify.atlassian.net/browse/ATB-1448)
[ATB-1448]: https://govukverify.atlassian.net/browse/ATB-1448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1448 + ATB-1444 |  Update README and Update base CloudFormation stack versions

.gitignore, feature-tests/jest-cucumber-config.js, feature-tests/jest.config.ts, feature-tests/package.json, feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature, feature-tests/tests/resources/features/aisGET/InvokeMultipleUsers-HappyPath.feature, feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts, feature-tests/tests/resources/step-definitions/invoke-multiple-users-accounts.step.ts, feature-tests/yarn.lock, yarn.lock
implemented scenario to create multiple ais suspended users
- [ATB-1405](https://govukverify.atlassian.net/browse/ATB-1405)
[ATB-1405]: https://govukverify.atlassian.net/browse/ATB-1405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1405: Create Multiple AIS Suspended Users

src/handlers/status-retriever-handler.ts
Added API Gateway event into debug logs
Need to get more details into log message to resolve issues with int testing
- [ATB-1459](https://govukverify.atlassian.net/browse/ATB-1459)
Logging change only
[ATB-1459]: https://govukverify.atlassian.net/browse/ATB-1459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1459: print userId in debug mode

README.md, stack-orchestration/build_pipelines.sh, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-main-pipeline/parameters.json, stack-orchestration/development_pipelines.sh, stack-orchestration/integration_pipelines.sh, stack-orchestration/production_pipelines.sh, stack-orchestration/staging_pipelines.sh
Updated stack orchestration config because we needed to use the new pipeline version to run feature tests
To allow feature tests to update items in DynamoDB, the dev-platform team had to create a new version of the pipeline with a updated TestPolicy that has the appropriate DynamoDB permissions.
- [ATB-1463](https://govukverify.atlassian.net/browse/ATB-1463)
Update ais-main-pipelines in dev and build only
[ATB-1463]: https://govukverify.atlassian.net/browse/ATB-1463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1459: updated to use latest version of pipelines and update config for build

package.json, yarn.lock
Reverted aws-sdk versions that caused failures in execution
- [ATB-1477](https://govukverify.atlassian.net/browse/ATB-1477)
Before:
No errors after reverting to previous versions:
[ATB-1477]: https://govukverify.atlassian.net/browse/ATB-1477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1477 Changed versions of aws-sdk deps

feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature, feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
- [ATB-1486](https://govukverify.atlassian.net/browse/ATB-1486)
[ATB-1486]: https://govukverify.atlassian.net/browse/ATB-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1486: Added tests to validate values when users has a successfull pswd and id reset

src/infra/core/template.yaml, src/infra/main/template.yaml, stack-orchestration/configuration/di-account-interventions-integration-admin/tags.json, stack-orchestration/configuration/di-account-interventions-production-admin/tags.json, stack-orchestration/configuration/di-id-reuse-core-build-admin/tags.json, stack-orchestration/configuration/di-id-reuse-core-dev-admin/tags.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/tags.json
ATB-1518 - Replace OwnerTagValue to team contact email
Replace OwnerTagValue to team contact email to  >  [interventions@digital.cabinet-office.gov.uk] 
Team contact email has now been created
- [ATB-1518](https://govukverify.atlassian.net/browse/ATB-1518)
[ATB-1518]: https://govukverify.atlassian.net/browse/ATB-1518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1518 | Replace OwnerTagValue to team contact email

src/specs/api.yaml
[ATB-1526](https://govukverify.atlassian.net/browse/ATB-1526)
Updated email in OAS.
The email in question has been set up and now we are able to put the correct email in the spec.
Passes `yarn lint:spec`:
[ATB-1526]: https://govukverify.atlassian.net/browse/ATB-1526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB 1526 | Updated email parameter in Api Spec

feature-tests/package.json, package.json, src/contract-testing/ais-api-provider.pact.test.ts, src/contract-testing/pacts/samplePact.json, src/contract-testing/test-helpers/mock-server.ts, yarn.lock
[ATB-1088](https://govukverify.atlassian.net/browse/ATB-1088)
Cover work to write provider tests against our account status API
To assert the correct behaviour of the API
Tested locally, retrieved pact files locally and tested against them:
[ATB-1088]: https://govukverify.atlassian.net/browse/ATB-1088?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1088 | AIS API Provider Test

src/contract-testing/test-helpers/mock-server.ts
[ATB 1533](https://govukverify.atlassian.net/browse/ATB-1533)
Disclosure of version information, usually overlooked by developers but disclosed by default by the systems and frameworks in use, can pose a significant security risk depending on the production environement.
Once this information is public, attackers can use it to identify potential security holes or vulnerabilities specific to that version.
Furthermore, if the published version information indicates the use of outdated or unsupported software, it becomes easier for attackers to exploit known vulnerabilities. They can search for published vulnerabilities related to that version and launch attacks that specifically target those vulnerabilities.
Passes pact tests:
Passes SonarCube quality check:
=> ATB 1533 | Amend SonarCube security hotspot

.github/workflows/manual-publish-alarm-to-dev.yaml, .github/workflows/manual-publish-core-to-dev.yaml, .github/workflows/manual-publish-main-to-dev.yaml, .github/workflows/merge-alarm-to-main.yaml, .github/workflows/merge-core-to-main.yaml, .github/workflows/merge-main-to-main.yaml, feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
ATB-1536 | Update devplatform-upload-action to v3.5 to make use of escape hatch functionality to skip Canary Deployment
devplatform-upload-action to v3.5 
Update devplatform-upload-action to v3.5 to make use of escape hatch functionality to skip Canary Deployment when begin  implementation  [Rollback Recovery Guidance | Skip Lambda canary deployments](https://govukverify.atlassian.net/wiki/spaces/PLAT/pages/3836051600/Rollback+Recovery+Guidance#Skip-Lambda-canary-deployments)  +  [Release v3.5 - Canary skip flag set in artifact metadata · govuk-one-login/devplatform-upload-action](https://github.com/govuk-one-login/devplatform-upload-action/releases/tag/v3.5)
- [ATB-1536](https://govukverify.atlassian.net/browse/ATB-1536)
[ATB-1536]: …
=> ATB-1536 | Update devplatform-upload-action to v3.5 to make use of escape hatch functionality to skip Canary Deployment

README.md
ATB-1523 |  Update README pipeline versions table
Updated AIS README pipeline versions table 
To keep consistent 
- [ATB-1523](https://govukverify.atlassian.net/browse/ATB-1523)
[ATB-1523]: https://govukverify.atlassian.net/browse/ATB-1523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1523 | Update README pipeline versions table

src/infra/alarm/template.yaml
ATB-1564 | Include runbook page link in the description of all our Alarms
Added in new Parameter referencing our RunBook URL 
So that there is easy access to our Runbook if needed to resolve any errors 
- [ATB-1564](https://govukverify.atlassian.net/browse/ATB-1564)
Not able to test in Dev because no Alert Configuration set up for this environment, would need to go through to build and then attempt to trigger to view. 
[ATB-1564]: https://govukverify.atlassian.net/browse/ATB-1564?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1564 | Include runbook page link in the description of all our Alarms

feature-tests/apiEndpoints/endpoints.ts, feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature, feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts, feature-tests/utils/dynamo-database-methods.ts, feature-tests/utils/send-sns-message.ts, feature-tests/utils/utility.ts, yarn.lock
Added Method to send message to SNS Delete Topic
Added Happy Path Scenario for Delete AIS Tests
Updated Happy Path Steps with new tests
Update Endpoints.ts file with SNS Topic
Feature Test added, scenario to send a message to SNS delete Topic to mark a Users AIS Record as deleted
Test required to cover Delete feature delivered for AIS Solution
- [ATB-1506](https://govukverify.atlassian.net/browse/ATB-1506)
New Feature tests added:
[ATB-1506]: https://govukverify.atlassian.net/browse/ATB-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1506: AIS-Feature-Tests - Added method to send SNS delete request for AIS User

feature-tests/package.json, feature-tests/yarn.lock, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-dev-admin/ais-main-pipeline/parameters.json
Forced merge to fix pipeline feature tests
Broken ais-main pipeline in build
Published into dev and tested in pipeline
=> Pipeline issues

feature-tests/run-tests.sh, feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
Due to failing regression tests we have updates some steps with additional waits in the .steps.ts file
Uopdate steps.ts file with waits on Then Step for Test Scenario: Scenario Outline: Happy Path - Get Request to /ais/userId - allowable Transition from <originalAisEventType> to <allowableAisEventType> - Get Request to /ais/userId - Returns expected data with history values
To resolve failing regression tests
- [ATB-1570](https://govukverify.atlassian.net/browse/ATB-1570)
[ATB-1570]: https://govukverify.atlassian.net/browse/ATB-1570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1570 : Feature-Tests - Update failing pipeline regression test with additional waits

feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-UnHappyPath.feature, yarn.lock
- [ATB-1549](https://govukverify.atlassian.net/browse/ATB-1549)
[ATB-1549]: https://govukverify.atlassian.net/browse/ATB-1549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1549: Added Unhappy path Scenarios to validate Egress Queue error messages

src/infra/main/template.yaml
ATB-1574 | Add in SSM Parameters for our Account Deletion Processor Queue
Added in SSM Parameters for our Account Deletion Processor Queue and DLQ so that they can be referenced  in our Alarm template for our Account Deletion Processor SQS queues alarms that have been created as part of  - https://govukverify.atlassian.net/browse/ATB-1566 
Allows our Alarms to fetch the right value
- [ATB-1574](https://govukverify.atlassian.net/browse/ATB-1574)
[ATB-1574]: https://govukverify.atlassian.net/browse/ATB-1574?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1574 | Add in SSM Parameters for our Account Deletion Processor Queue

src/infra/alarm/template.yaml, src/infra/main/template.yaml
Created CloudWatch alarms to monitor API Gateway errors. Based on latency and HTTP 4XX/5XX response status codes.
Also removed /${AWS::StackName}/PrivateRestApi/ID SSM parameter as this does not seem to be used.
To raise alerts for relevant API Gateway CloudWatch metrics 
- [ATB-1562](https://govukverify.atlassian.net/browse/ATB-1562)
[ATB-1562]: https://govukverify.atlassian.net/browse/ATB-1562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1562 Create alarms for API Gateway 4XX, 5XX, and Latency errors

src/infra/alarm/template.yaml
ATB-1566 | Create extra alarms for SQS Queues and Lambdas
Added in an alarm for Account Deletion Processor Queue and the DLQ too for the metric > `ApproximateAgeOfOldestMessage` 
Added in Alarms for our Lambdas relating to the metrics `Errors` and `Throttles` 
To make sure we are monitoring all components of our solution 
- [ATB-1566](https://govukverify.atlassian.net/browse/ATB-1566)
[ATB-1566]: https://govukverify.atlassian.net/browse/ATB-1566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1566 | Create alarms for SQS Queues and Lambdas

src/infra/alarm/template.yaml
ATB-1566 | Fix Queue name
Fixed Queue Name 
Wrong name 
- [ATB-1566](https://govukverify.atlassian.net/browse/ATB-1566)
[ATB-1566]: https://govukverify.atlassian.net/browse/ATB-1566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1566 | Fix Queue name

feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature, feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts, feature-tests/utils/enhanced-ais-events.ts, feature-tests/utils/send-sqs-message.ts, yarn.lock
implemented feature-test to send in additional fields in the 'Interventions' section for a AIS event Type
To increase the Coverage
- [ATB-1483](https://govukverify.atlassian.net/browse/ATB-1483)
[ATB-1483]: https://govukverify.atlassian.net/browse/ATB-1483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1483: Added feature-tests to to send in additional fields

stack-orchestration/configuration/di-account-interventions-integration-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-production-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-dev-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-main-pipeline/parameters.json
ATB-1640 | Update main pipeline Parameter LambdaDeploymentPreference
Updated main pipeline Parameter LambdaDeploymentPreference: 
Dev - None 
Build - None 
Staging - None 
Integration - Canary10Percent10Minutes
Production - Canary10Percent10Minutes
This parameter is required to be set so that we can utilise the skip canary feature for canary deployment. 
- [ATB-1640](https://govukverify.atlassian.net/browse/ATB-1640)
[ATB-1640]: https://govukverify.atlassian.net/browse/ATB-1640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1640 | Update main pipeline Parameter LambdaDeploymentPreference

stack-orchestration/configuration/di-account-interventions-integration-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-production-admin/ais-main-pipeline/parameters.json
ATB-1671 | Update Stack Orchestration ArtifactSourceBucketArn value
`ArtifactSourceBucketArn` changed due to Include Promotion Parameter set to No so needed to fetch the new value after switching it to Yes in Staging. 
Changed after Include Promotion Parameter set to NO. To avoid in the future will disable transition instead. 
- [ATB-1671](https://govukverify.atlassian.net/browse/ATB-1671)
[ATB-1671]: https://govukverify.atlassian.net/browse/ATB-1671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1671 | Update Stack Orchestration ArtifactSourceBucketArn value

.github/workflows/manual-publish-alarm-to-dev.yaml, .github/workflows/manual-publish-core-to-dev.yaml, .github/workflows/manual-publish-main-to-dev.yaml, .github/workflows/merge-alarm-to-main.yaml, .github/workflows/merge-core-to-main.yaml, .github/workflows/merge-main-to-main.yaml
ATB-1657 | Update Dev Platform upload action to v3.8.1
Updated devplatform-upload-action to V3.8.1 
This change fixes a bug with displaying time in Dynatrace - https://github.com/govuk-one-login/devplatform-upload-action/releases/tag/v3.8.1 
- [ATB-1657](https://govukverify.atlassian.net/browse/ATB-1657)
[ATB-1657]: https://govukverify.atlassian.net/browse/ATB-1657?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1657 | Update Dev Platform upload action to v3.8.1

src/infra/main/template.yaml
updated Orchs VPC and VPCE IDs for new Int & Prod AWS accounts
Int & Prod parameters values changed in main template
Orch Tech Lead requested change.
[Slack Chat](https://gds.slack.com/archives/D063S49L8G2/p1718799723220259)
Int & Prod changes only
=> bau: updated Orchs VPC and VPCE IDs for new Int & Prod AWS accounts

stack-orchestration/configuration/di-account-interventions-integration-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-account-interventions-production-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-dev-admin/ais-main-pipeline/parameters.json, stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-main-pipeline/parameters.json
ATB-1794 | Stack Orchestration change Param name from LambdaDeploymentPreference to LambdaCanaryDeployment
Stack Orchestration json file parameter name from `LambdaDeploymentPreference` to `LambdaCanaryDeployment` to keep Stack Orchestration correct. 
Incorrect parameter name being referenced. 
- [ATB-1794](https://govukverify.atlassian.net/browse/ATB-1794)
[ATB-1794]: https://govukverify.atlassian.net/browse/ATB-1794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1794 | Stack Orchestration change Param name from LambdaDeploymentPreference to LambdaCanaryDeployment

feature-tests/package.json, feature-tests/yarn.lock, package.json, yarn.lock
- [ATB-1809](https://govukverify.atlassian.net/browse/ATB-1809)
=> ATB-1809 | BAU - bumped deps

feature-tests/package.json, feature-tests/yarn.lock, package.json, yarn.lock
Resolved vulnerability warning
Bumped dependencies
https://github.com/govuk-one-login/account-interventions-service/security/dependabot/14
- [ATB-1815](https://govukverify.atlassian.net/browse/ATB-1815)
[ATB-1815]: https://govukverify.atlassian.net/browse/ATB-1815?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1815: resolved vulnerability warning

package.json, src/infra/main/template.yaml
updated the main package.json file to checok for eslint errors for each commit
To check for eslint errors in feature-tests
- [ATB-1851](https://govukverify.atlassian.net/browse/ATB-1851)
[ATB-1851]: https://govukverify.atlassian.net/browse/ATB-1851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> ATB-1851: Check Eslint in feature-tests

.github/dependabot.yaml, feature-tests/package.json, feature-tests/run-tests.sh, feature-tests/yarn.lock, package.json, yarn.lock
Bumped Dependencies
Package.json
BAU
Deployed and ran in dev
=> BAU: bumped dependencies

package.json, src/handlers/txma-handler.ts, src/infra/main/template.yaml, stack-orchestration/build_pipelines.sh, stack-orchestration/development_pipelines.sh, stack-orchestration/integration_pipelines.sh, stack-orchestration/production_pipelines.sh, stack-orchestration/staging_pipelines.sh, yarn.lock
- Create a new (placeholder) lambda
- Include all permissions, logging, metrics etc... for the lambda
- Set a trigger on the lambda to execute on the TxMA Ingress SQS queue
- Disable the lambda on all environments other than dev
- Disable the Account Interventions processor on dev 
https://govukverify.atlassian.net/browse/OLH-2188
=> OLH-2188 Add new lambda that listens to TxMA events

package.json, yarn.lock
-  Bump version of cross-spawn to 7.0.5
=> fix CVE-2024-21538

src/infra/main/template.yaml
Delete old permissions and policies related to the account deletions SNS topic
We no longer use the account deletions SNS topic
=> remove sns topic

.github/workflows/acceptance-checks.yaml
Replaced Sonar Github action
Old action is deprecated and no longer works.
- https://govukverify.atlassian.net/browse/OLH-2455
- New github action confirmed working
=> BAU-Replace-Sonar-Github-Action

src/infra/main/template.yaml
Added IPV Core VPC's to allow lists
IPV need to connect to AIS’s private API to facilitate intervention checks
- [OLH-2759](https://govukverify.atlassian.net/browse/OLH-2759)
Only testable in higher envs
[OLH-2759]: https://govukverify.atlassian.net/browse/OLH-2759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OLH-2759: Add IPV VPC and Endpoint IDs for Staging, Int & Prod

src/handlers/status-retriever-handler.ts
=> BAU: added dummy logging line

stack-orchestration/configuration/di-account-interventions-integration-admin/checkov-hook/parameters.json, stack-orchestration/configuration/di-account-interventions-production-admin/checkov-hook/parameters.json
Update checkov stack by making sure stack parameter FailureMode is set to WARN. 
Introduced new parameter FailureMode within integration and production configuration files
Raising a P4 incident with AWS Control Tower as it is blocked from updating it's landing zone settings by a Cloudformation hook which is deployed across the organisation in many accounts. The impact of this is that FOG is unable to update regions in control tower and it also blocks Landing Zone Accelerator meaning that no new AWS accounts can be vended until this issue is resolved.
See original work ticket PSREGOV-2727: https://govukverify.atlassian.net/browse/PSREGOV-2727
See support request to resolve PSREDEV-2528: FOG : https://govukverify.atlassian.net/browse/PSREDEV-2528
Successful resolution of this incident …
=> FPAD-5539: Added FailureMode parameter to checkov stack

feature-tests/package.json, feature-tests/yarn.lock, package.json, yarn.lock
FPAD-5588: Adding resolutions to set form-data
form-data has malware
upgraded to a safer version
Passed deployed pipeline tests
=> FPAD-5588: Adding resolutions to set form-data

CODEOWNERS
* Updated the name of team 1 for the new GitHub group.
* The team name has changed due to the move of SSF and AIS.
- [FPAD-5491](https://govukverify.atlassian.net/browse/FPAD-5491)
* N/A - config change
[FPAD-5491]: https://govukverify.atlassian.net/browse/FPAD-5491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> FPAD-5491: Updated team 1 name to Fraud Mercury team
