- .github/dependabot.yaml
Added dependabot 
added yaml file under .github folder, this is lifted from the id reuse repo
automatically flag outdated depedencies
- [ATB-992](https://govukverify.atlassian.net/browse/ATB-992)
[ATB-992]: https://govukverify.atlassian.net/browse/ATB-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-992 | Dependabot

- src/handlers/account-deletion-processor-handler.ts
- src/handlers/tests/account-deletion-processor-handler.test.ts
- src/services/dynamo-database-service.ts
- src/services/test/dynamo-database-service.test.ts
- Refactor/ change the condition expression
- Re-driving in the queue based on condition expression
- Updated UTs
- Make sure that a user is not re-driven in the queue when the user does not exist (ConditionalCheckFailedException)
- Make sure that the users are re-driven if the error is anything but a Conditional Check Exception.
- [ATB-1136](https://govukverify.atlassian.net/browse/ATB-1136)
Scenario 1: When the user_id does not exist in the table, and an error is logged when the user_id is trying to be deleted.
Scenario 2: Adding user_id, deleting user_id, marks as deleted correctly.
UTs:
Logs (re; ConditionalCheckFailedException)
If it isn't a conditional check exception, the SQS record will be sent to the queue to be retried:
When the user does not exist, a log line is logged, and the …
> ATB-1136 | Refactor account-deletion-processor

- package.json
- src/handlers/status-retriever-handler.ts
- src/handlers/tests/status-retriever-handler.test.ts
[ATB-1190](https://govukverify.atlassian.net/browse/ATB-1190)
Added logic and unit tests to cover the scenario of encoded path parameters along with updating unit tests to cover this.
Currently the status retriever handler could not handle encoded path parameters, this change is to ensure it can.
Locally, via unit tests. Full code coverage:
API Gateway, correctly decodes the user Id and retrieves the record that is matched against it:
[ATB-1190]: https://govukverify.atlassian.net/browse/ATB-1190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1190: Ensure status-retriever can handle encoded path parameters

- src/specs/api.yaml
API Spec documentation change only
Clarified subject id is the internal DI pairwise identifier
- [ATB-1222](https://govukverify.atlassian.net/browse/ATB-1222)
Swagger doc change only - being rendered in Swagger Editor okay
[ATB-1222]: https://govukverify.atlassian.net/browse/ATB-1222?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1222: clarified subject id is the internal DI pairwise identifier and removed throttling error

- feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature
- feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
- feature-tests/utils/invoke-apigateway-lambda.ts
fixed local run error with SQS payload being a string instead of object and reworded test scenario titles and matcher strings to improve readability
Local feature runs were failing
- [ATB-1249](https://govukverify.atlassian.net/browse/ATB-1249)
[ATB-1249]: https://govukverify.atlassian.net/browse/ATB-1249?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1249: fixed local run error and reworded test scenario titles and matcher strings to improve readability

- src/infra/main/template.yaml
This ticket merges changes necessary to ensure that TxMA can ready messages from our egress queue
Added permission for TxMA account to use the key that encrypts messages in the queue
Allow integration with TxMA for outgoing messages
- [ATB-1270](https://govukverify.atlassian.net/browse/ATB-1270)
Successfully deployed changes to AWS account
[ATB-1270]: https://govukverify.atlassian.net/browse/ATB-1270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1270 | Integrate TxMAEgress queue

- src/infra/main/template.yaml
[ATB-1243](https://govukverify.atlassian.net/browse/ATB-1243)
Ensuring API GW Rest API log group has a subscription to CSLS
Need to send logs to Cyber monitoring tool (Splunk)
Currently no access to splunk to check if logs are successfully sent, will update this in due course
AccessLogGroup was successfully created, as seen in API GW:
Created log group for Invoke Private API function:
Successfully publishes logs to the log group when function is invoked:
[ATB-1243]: https://govukverify.atlassian.net/browse/ATB-1243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1243: Enable API Gateway logging along with CSLS subscription

- package.json
Added iac lint to linting phase
Linting phase now includes linting of template.yaml's
Was not being linted
- [ATB-1384](https://govukverify.atlassian.net/browse/ATB-1384)
Tested locally
[ATB-1384]: https://govukverify.atlassian.net/browse/ATB-1384?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1384: added iac lint to linting phase

- feature-tests/apiEndpoints/endpoints.ts
- src/infra/main/template.yaml
Configured intervention processor to consume messages from TxMA
Main template - In dev and build envs creates a dummy queue but for envs staging and upwards utilises the TxMA provided queue
Enable TxMA consumer
- [ATB-1073](https://govukverify.atlassian.net/browse/ATB-1073)
[ATB-1073]: https://govukverify.atlassian.net/browse/ATB-1073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1073: configured intervention processor to consume messages from TxMA

- src/infra/core/template.yaml
Added tags to enable backup and deletion protection
DynamoDB config
Enable backups via AWS Backup
- [ATB-1387](https://govukverify.atlassian.net/browse/ATB-1387)
Only testable once tag applied.
[ATB-1387]: https://govukverify.atlassian.net/browse/ATB-1387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1387: Added tags to enable backup and deletion protection

- src/infra/alarm/template.yaml
- src/infra/main/template.yaml
This PR merges changes as per tickets:
- https://govukverify.atlassian.net/browse/ATB-1367
- https://govukverify.atlassian.net/browse/ATB-1369
This PR changes:
- main template: added SSM parameter resources to store the name of the TxMA Egress SQS queue and its DLQ, to be read in by the alarm template
- alarm template: added Cloudwatch alarm resources to track:
- TxMAEgressDLQHasMessages - threshold 1, period 60sec, eval period 1, Low Severity Alert
- TxMAEgressDLQTooManyMessages - threshold 10, period 60sec, eval period 1, High Severity Alert
- TxMAEgressQueueTooManyMessages - threshold 50, period 60sec, eval period 1, High Severity Alert
- TxMAEgressQueueHasBacklog - threshold 10, period 60sec, eval period 1, Low Severity Alert
- TxMAEgressQueueProcessingSlowly - threshold 60, period …
> ATB-1367 | TxMA Egress Queue and DLQ Alarms

- package.json
- src/contract-testing/amf-ais-consumer.pact.test.ts
- src/contract-testing/txma-ais-consumer.pact.test.ts
- yarn.lock
This PR merges changes to implement consumer contract testing on the consumer side of AIS
- added pact as a dependency
- added 2 new test files to run contract testing for AIS interaction with TxMA (ingress messages) and AMF (delete user account flow). These test generate two separate contracts when running 
- added appropriate commands to run those tests
Did not add the generated pact files as tracked files as those should be generated when the tests run to ensure that they are up to date. 
implement contract testing
- [ATB-1086](https://govukverify.atlassian.net/browse/ATB-1086)
test pass when running locally and contracts are generated
[ATB-1086]: https://govukverify.atlassian.net/browse/ATB-1086?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
> ATB-1086 | Pact Consumer Tests

- src/commons/build-partial-update-state-command.ts
- src/commons/test/build-partial-update-state-command.test.ts
… requires new user action
Deleted reprovedIdentityAt and resetPasswordAt when new user actions are needed.
When a new user action is needed on the account,  reprovedIdentityAt and resetPasswordAt are not expected to be present anymore.
- [ATB-1414](https://govukverify.atlassian.net/browse/ATB-1414)
DynamoDB entry before applying Intervention with code 04 (requires password update)
After applying intervention (no resetPasswordAt):
[ATB-1414]: https://govukverify.atlassian.net/browse/ATB-1414?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB 1414 reset reprovedIdentityAt and resetPasswordAt 

- src/commons/build-partial-update-state-command.ts
- src/services/account-states/config.ts
- src/services/test/account-state-engine.test.ts
Added case when an AUTH_PASSWORD_RESET_SUCCESSFUL_FOR_TEST_CLIENT event is received
Added AUTH_PASSWORD_RESET_SUCCESSFUL_FOR_TEST_CLIENT in the configuration filw
The case was not treated, and it would end up returning a non-retriable error.
- [ATB-1413](https://govukverify.atlassian.net/browse/ATB-1413)
Sent an AUTH_PASSWORD_RESET_SUCCESSFUL_FOR_TEST_CLIENT event
Egress message:
[ATB-1413]: https://govukverify.atlassian.net/browse/ATB-1413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1413 AUTH_PASSWORD_RESET_SUCCESSFUL_FOR_TEST_CLIENT 

- src/commons/test/build-partial-update-state-command.test.ts
- src/contract-testing/amf-ais-consumer.pact.test.ts
- src/contract-testing/txma-ais-consumer.pact.test.ts
- src/data-types/interfaces.ts
- src/handlers/interventions-processor-handler.ts
- src/handlers/tests/interventions-processor-lambda.test.ts
- src/handlers/tests/status-retriever-handler.test.ts
- src/infra/main/samconfig.toml
- src/infra/main/template.yaml
- src/services/account-states/account-state-engine.ts
- src/services/send-audit-events.ts
- src/services/test/account-state-engine.test.ts
- src/services/test/dynamo-database-service.test.ts
- src/services/test/send-audit-events.test.ts
- src/services/test/validate-event.test.ts
- src/services/validate-event.ts
- yarn.lock
This PR merges changes not to publish egress messages to TxMA when an user action event is received (reset password/id successful) for a user who does not have an active intervention on their account.
- added check to the send audit event flow to see if the event should be ignored
- updated unit tests to assert that call to sqs mock doesn't happen when event is excluded
- linted tests
reduce noise 
- [ATB-1429](https://govukverify.atlassian.net/browse/ATB-1429)
Coverage maintained
Changes deployed to AWS.
- sent a password reset successful event for a non-existing user
- sent an id reset event for a non-existing user
- sent a psw reset successful event for a user that exists in the DB but has no active intervention
- sent an id reset event for a user that exists in the DB but has no …
> ATB-1429: Reduce egress messages noise

- src/infra/main/template.yaml
[ATB-1433](https://govukverify.atlassian.net/browse/ATB-1433)
In order for Auth and Orch to call our Private API from within their VPC, they have create an execute-api VPC Endpoint to enable calls to AIS API via AWS networks
Otherwise will not be able to discover and connect to the AIS API
Tested locally, passes linting:
Stack successfully deploys:
[ATB-1433]: https://govukverify.atlassian.net/browse/ATB-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1433 | Add VPC Endpoint IDs for Auth/Orch

- src/infra/main/template.yaml
- yarn.lock
Get VPC Endpoint IDs added to REST API
Refactored condition to proper if statement instead of conditional
VPC Endpoint IDs were not added to REST API
- [ATB-1433](https://govukverify.atlassian.net/browse/ATB-1433)
Only testable in staging and beyond
[ATB-1433]: https://govukverify.atlassian.net/browse/ATB-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1433: Refactored condition to proper if statement instead of conditional

- src/infra/main/template.yaml
[ATB-1433](https://govukverify.atlassian.net/browse/ATB-1433)
In order for Auth and Orch to call our Private API from within their VPC, they have create an execute-api VPC Endpoint to enable calls to AIS API via AWS networks
Otherwise will not be able to discover and connect to the AIS API
Deployed to dev and staging - final checks will be done in int once merged
[ATB-1433](https://govukverify.atlassian.net/browse/ATB-1433)
[ATB-1433]: https://govukverify.atlassian.net/browse/ATB-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ATB-1433]: https://govukverify.atlassian.net/browse/ATB-1433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1433: added VPC Endpoint IDs to API provided by Auth and Orch

- src/handlers/interventions-processor-handler.ts
This PR merges a small change to fix a code smell reported by sonar cloud
- turned `||` into `??` in intervention processor handler file
- added sensitive info pre-fix to debug line containing user id, removed sensitive info prefix to debug line containing intervention name 
fix code smell
- [ATB-1466](https://govukverify.atlassian.net/browse/ATB-1466)
Deployed changes to AWS account and run feature tests suites
Manually check that metric is still being logged as expected
no code smell reported: https://sonarcloud.io/summary/new_code?id=govuk-one-login_account-interventions-service&pullRequest=180
> ATB-1466: Fix Code Smell

- feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature
- feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
[ATB 1423](https://govukverify.atlassian.net/browse/ATB-1423)
Added auditLevel field from intervention response as an example
To validate the field in feature tests
Passes all feature tests:
> ATB-1423 | 'Add AuditLevel' field from Intervention response as a example and validated field in feature-tests

- feature-tests/utils/ais-events.ts
[ATB-1449](https://govukverify.atlassian.net/browse/ATB-1449)
As per ATB-1365, the following fields will need to be added to and validated against:
- originating_component_id
- originator_reference_id
- requester_id
- event_id
To mirror events passed in so they can be correctly validated, mirrored against the JSON files passed in:
Passes tests locally:
[ATB-1449]: https://govukverify.atlassian.net/browse/ATB-1449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB 1449 | Add new fields to ais-event.ts file for TxMA egress message for Fraud team

- feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature
- feature-tests/tests/resources/features/aisGET/InvokeMultipleUsers-HappyPath.feature
- feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
- [ATB-1476](https://govukverify.atlassian.net/browse/ATB-1476)
[ATB-1476]: https://govukverify.atlassian.net/browse/ATB-1476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1476: Update feature file steps to match step defs

- .eslintrc.js
- jest.config.js
- package.json
- src/commons/build-partial-update-state-command.ts
- src/commons/history-string-builder.ts
- src/commons/test/build-partial-update-state-command.test.ts
- src/data-types/interfaces.ts
- src/handlers/interventions-processor-handler.ts
- src/handlers/status-retriever-handler.ts
- src/infra/main/template.yaml
- src/services/app-config-service.ts
- src/services/dynamo-database-service.ts
- src/services/test/app-config-service.test.ts
- src/services/test/dynamo-database-service.test.ts
- src/services/test/validate-event.test.ts
1. Added env var to keep retention period
2. Because we're not allowed to do a SET and a REMOVE on the same attribute in one operation, it would have been inefficient time-wise to perform and wait for 2 dynamodb updates, hence the reason why I opted to compute the history list and replace it
To adhere with the DI data retention period
- [ATB-1447](https://govukverify.atlassian.net/browse/ATB-1447)
1. new env var present
2. For testing purposes, set it to 86400 to make sure we have expired items
3. All items in the history that will be removed:
4. Event sent:
5. Results:
[ATB-1447]: https://govukverify.atlassian.net/browse/ATB-1447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1447 Remove history item if its age exceeds 2 years

- src/commons/build-partial-update-state-command.ts
- src/commons/test/build-partial-update-state-command.test.ts
Added missing updateExpression for update operation when event was a user led action
- [ATB-1484](https://govukverify.atlassian.net/browse/ATB-1484)
Given we have this scenario:
We're sending in a AUTH_PASSWORD_RESET_SUCCESSFUL event:
Feature tests passing:
[ATB-1484]: https://govukverify.atlassian.net/browse/ATB-1484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1484 | Fixed UserLed Actions failures

- src/data-types/interfaces.ts
- src/services/send-audit-events.ts
- src/services/test/send-audit-events.test.ts
This PR merges changes to include all intervention attribute fields from the a source intervention event into the outgoing message to txma
- in the send audit event file, when the egress event is built, its extension attribute will not contain all of the fields contained under the intervention field in the original event
- updated interface and unit tests
Include all intervention information 
- [ATB-1478](https://govukverify.atlassian.net/browse/ATB-1478)
added unit test for new logic
deployed changes to AWS account and sent events with extra fields:
applied event
event in the future
[ATB-1478]: https://govukverify.atlassian.net/browse/ATB-1478?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1478: TxMA Egress Messages needs to include all `intervention` attributes in outgoing messages

- feature-tests/run-tests.sh
- feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature
- feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
- [ATB-1479](https://govukverify.atlassian.net/browse/ATB-1479)
[ATB-1479]: https://govukverify.atlassian.net/browse/ATB-1479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1479: Update parameter names for history tests

- feature-tests/Dockerfile
[ATB-1491](https://govukverify.atlassian.net/browse/ATB-1491)
Changed docker file to allow it to install node 20 correctly
the package.json in feature tests was forcing a node20 version, docker was installing node 18 and encountering errors when trying to build.
Docker builds locally:
Feature tests still passing:
[ATB-1491]: https://govukverify.atlassian.net/browse/ATB-1491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB 1491 - Fix docker container issue with node 20.x

- src/data-types/constants.ts
- src/services/send-audit-events.ts
Added all non intervention codes to the constant that's holding them.
At the moment, only codes for AUTH_PASSWORD_RESET_SUCCESSFUL and IPV_IDENTITY_ISSUED are excluded from the allowable_interventions array that’s being sent in the egress message to TxMA.
We need to exclude the codes for AUTH_PASSWORD_RESET_SUCCESSFUL_FOR_TEST_CLIENT as well.
- [ATB-1485](https://govukverify.atlassian.net/browse/ATB-1485)
Before:
After:
[ATB-1485]: https://govukverify.atlassian.net/browse/ATB-1485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB 1485 | Exclude AUTH_PASSWORD_SUCCESSFUL_FOR_TEST_CLIENT codes from allowable_interventions

- feature-tests/apiEndpoints/endpoints.ts
- feature-tests/run-tests.sh
- feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature
- feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
- feature-tests/utils/ais-events-responses.ts
- feature-tests/utils/send-sqs-message.ts
- feature-tests/utils/utility.ts
- webpack.config.ts
Added SQS Egress Queue methods to purge and receive the messages
To validate the next allowable intervention types for the ais event types in the SQS Egress Queue messages
- [ATB-1473](https://govukverify.atlassian.net/browse/ATB-1473)
[ATB-1473]: https://govukverify.atlassian.net/browse/ATB-1473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1473: Add Egress Queue Methods

- feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature
- feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
- feature-tests/utils/utility.ts
Added scenarios to validate history items that exceeds 2 years
To improve the coverage
- [ATB-1482](https://govukverify.atlassian.net/browse/ATB-1482)
[ATB-1482]: https://govukverify.atlassian.net/browse/ATB-1482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1482: Validate History values does not exceed 2 years

- feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-HappyPath.feature
- feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
- feature-tests/utils/ais-events-responses.ts
- feature-tests/utils/ais-events.ts
userActionPswResetSuccessForTestClient added as ais-event and ais-event-responses 
Update TxMA Egress message step with new event type
New AIS event type has been added (userActionPswResetSuccessForTestClient) which functions the same as (userActionPswResetSuccess), this event type has been included in the test scenarios where (userActionPswResetSuccess) is already included, with the same exceptions of validation
The (userActionPswResetSuccessForTestClient) AIS event type is required a default event_type 
- [ATB-1487](https://govukverify.atlassian.net/browse/ATB-1487)
All tests passed in DEV:
All Linting checks passed
[ATB-1487]: https://govukverify.atlassian.net/browse/ATB-1487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1487: Added new AIS Event Type (userActionPswResetSuccessForTestClient)

- src/infra/main/template.yaml
[ATB-1513](https://govukverify.atlassian.net/browse/ATB-1513)
updated `LOG_LEVEL` environment variable to `POWERTOOLS_LOG_LEVEL`
The environment variable that the powertools lambda logger dependency uses has been updated in the documentation to POWERTOOLS_LOG_LEVEL (the LOG_LEVEL is now a legacy name, although it is currently still being supported)
Locally, passes `yarn lint:iac`
Stack successfully deploys:
Shows in each lambdas environment variables in AWS:
Cloudwatch logs retain functionality:
[ATB-1513]: https://govukverify.atlassian.net/browse/ATB-1513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1513 | Update lambda log level environment variable

- .husky/pre-commit
- .husky/pre-push
- README.md
- package.json
- src/handlers/account-deletion-processor-handler.ts
- src/handlers/status-retriever-handler.ts
- yarn.lock
[ATB-1515](https://govukverify.atlassian.net/browse/ATB-1515)
Enabled Husky to lint and fix code on `git commit` and to run `yarn test` during `git push`. 
Get feedback faster if changes have broken unit tests
Runs `pre-commit` package on commit and unit tests on `git push`:
[ATB-1515]: https://govukverify.atlassian.net/browse/ATB-1515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB 1515 | Investigate and implement using Husky for pre-push hooks

- src/infra/alarm/template.yaml
ATB-1554 | Review Alarm Thresholds and Severities [Part 1 - looking at severities only]
Changed the following from High to Low:
- TxMAEgressQueueProcessingTooSlow
- TxMAEgressQueueTooManyMessages
- TxMAEgressDLQTooManyMessages
- TooManyInterventionNotAllowed
- TooManyInvalidEventsReceived
- TooManyInterventionEventStale
- InvalidHistoryString
Removed AverageTxMALatencyOver1Sec Alarm because we believe it will be too sensitive to have. 
Refining Alarm severities prior to integrating with Pager Duty 
- [ATB-1554](https://govukverify.atlassian.net/browse/ATB-1554)
[ATB-1554]: https://govukverify.atlassian.net/browse/ATB-1554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB -1554 | Updating Alarm Severities 

- feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-UnHappyPath.feature
- feature-tests/tests/resources/step-definitions/invoke-api-gateway-unhappy-path.step.ts
- src/infra/alarm/template.yaml
- [ATB-1551](https://govukverify.atlassian.net/browse/ATB-1551)
[ATB-1551]: https://govukverify.atlassian.net/browse/ATB-1551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1551: added unhappy path scenarios around history values

- src/commons/metrics.ts
- src/commons/test/metrics.test.ts
This PR merges changes needed to ensure that metrics only get logged with dimensions where those are relevant/expected. When using the add metric method and passing it dimensions to add, those dimensions are added to all of the metrics currently stored in the buffer. This causes dimensions being applied to metrics that should not have them. The proposed solution is to publish metric if any are stored before we add any dimensions, once the dimensions are added the buffer should be flushed (publish metrics) so that the passed dimensions are only used for the specific metric
- added logic inside the addMetric function to publish stored metrics (if any) before dimensions are added
- added logic inside the addMetric function to publish stored metrics after adding a metric with dimension so …
> Metric Dimensions

- feature-tests/tests/resources/features/aisGET/InvokeApiGateWay-UnHappyPath.feature
- feature-tests/tests/resources/step-definitions/invoke-api-gateway-unhappy-path.step.ts
- feature-tests/utils/invalid-ais-events.ts
Implemented unhappy path scenario for user led actions 
it should only update status on `IPV_IDENTITY_ISSUED` when `levelOfConfidence` equals `P2`. it shouldnt update if the level of confidence is other than p2
- [ATB-1552](https://govukverify.atlassian.net/browse/ATB-1552)
[ATB-1552]: https://govukverify.atlassian.net/browse/ATB-1552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1552:Implemented the unhappy path scenario for userActionIdResetSuccess

- src/infra/alarm/template.yaml
updated alarms with unit set to count
Missing unit definitions and some were using samplecount instead
To fix false alarms
- [ATB-XXXX](https://govukverify.atlassian.net/browse/ATB-1566)
> ATB-1566: updated alarms with unit set to count

- src/infra/alarm/template.yaml
This PR merges changes to remove the `ConfidenceLevelTooLow` Alarm
Rationale: this alarm is triggered when multiple IPV_IDENTITY_ISSUED events are received with a confidence level other than P2. This is creating a lot of noise as those events are legitimate events that users will generate, and when the related metric is logged we do not know the current status of the account and if it is in need of an identity reset, in which case the supplied confidence level is too low. 
As such this alarm is not currently giving us any useful information
I have left a comment on the monitoring runbook to flag this change
Deleted alarm from alarm template
reduce noise 
- [ATB-1580](https://govukverify.atlassian.net/browse/ATB-1580)
[ATB-1580]: https://govukverify.atlassian.net/browse/ATB-1580?atlOrigin=e …
> ATB-1580: Remove ConfidenceLevelTooLow alarm

- src/handlers/status-retriever-handler.ts
- src/infra/main/template.yaml
- src/specs/api.yaml
ATB-1650 | Update Api Spec and Lambda Permissions to enable Lambda Rollback through ClickOps
- Updated API Spec to reference to live instead of latest  
- Updated `AWS::Lambda::Permission` resource to reference Alias at the `FunctionName` property so that when the Trigger  is attached to our Alias version,  This is important so that if we ever need to rollback our Lambda / new version is created, the trigger will be attached to the correct version of the Lambda function and uses the latest version rather than any older version so no unexpected behaviour can take place. 
Testing out ClickOps as a Lambda Rollback Option 
- [ATB-1650](https://govukverify.atlassian.net/browse/ATB-1650)
**Status Retriever** 
Prior to Rollback:
After changing Alias - Rollback : 
**Interventions Processor** …
> ATB-1650 | Update API Spec and Lambda Permissions to enable Lambda Rollback through ClickOps

- stack-orchestration/configuration/di-id-reuse-core-build-admin/ais-main-pipeline/parameters.json
- stack-orchestration/configuration/di-id-reuse-core-dev-admin/ais-main-pipeline/parameters.json
- stack-orchestration/configuration/di-id-reuse-core-staging-admin/ais-main-pipeline/parameters.json
ATB-1672 | Set the Parameter LambdaCanaryDeployment to AllAtOnce in Dev - Staging Environments
Set the Parameter LambdaCanaryDeployment to AllAtOnce in Dev - Staging Environments 
Advised by Dev Platform to use AllAtOnce so that every environment will be able to use CodeDeploy for deployments - cannot be set to None as means that environments won't even use Canary Deployment. 
A requirement for Canary Deployment is that all environments need to be the same, however notice that it does take extra time for the deployment process so we can set the parameter to AllAtOnce for Dev - Staging and then Canary10Percent10Minutes for Integration and Production. 
- [ATB-1672](https://govukverify.atlassian.net/browse/ATB-1672)
[ATB-1672]: https://govukverify.atlassian.net/browse/ATB-1672?atlOrigin=eyJpI …
> ATB-1672 | Set the Parameter LambdaCanaryDeployment to AllAtOnce in Dev - Staging Environments

- src/infra/main/template.yaml
ATB-1678 | Change Parameter AlertingSNSLowAlertNotificationTopicARN in main template to ais-infra-alerting
- Parameter set to ais-infra-alerting instead 
Referring to infra-alerting previously 
- [ATB-1678](https://govukverify.atlassian.net/browse/ATB-1678)
[ATB-1678]: https://govukverify.atlassian.net/browse/ATB-1678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1678: Change Parameter AlertingSNSLowAlertNotificationTopicARN in main template to ais-infra-alerting

- .github/workflows/pact-test-api-provider.yaml
- .github/workflows/pact-test-message-consumer.yaml
This PR merges a small change in to correct the naming of an environment variable in the consumer pact testing workflow to allow pact to publish to the broker
Renamed `PROVIDER_APP_VERSION` --> `CONSUMER_APP_VERSION`
Allow publishing of pacts
> Fix : Pact workflow fix

- feature-tests/package.json
- feature-tests/tests/resources/step-definitions/invoke-api-gateway-happy-path.step.ts
- feature-tests/tests/resources/step-definitions/invoke-api-gateway-unhappy-path.step.ts
- feature-tests/utils/utility.ts
Optimise time to run the feature-tests in parallel
To reduce the time
- [ATB-1810](https://govukverify.atlassian.net/browse/ATB-1810)
[ATB-1810]: https://govukverify.atlassian.net/browse/ATB-1810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1810: Optimise time to run the feature-tests in parallel

- src/infra/main/template.yaml
fix E1022 - Join validation of parameters lint errors being reported by `sam validate` in SAM v1.124.0
GHA now using new SAM version which is now reporting new linting errors, hence switched to strings by sorrounding values with double quotes
Lint errors were blocking GHA validating checks
- [ATB-1858](https://govukverify.atlassian.net/browse/ATB-1858)
[ATB-1858]: https://govukverify.atlassian.net/browse/ATB-1858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ATB-1858: fixed E1022 - Join validation of parameters lint errors

- package.json
- src/infra/alarm/template.yaml
- src/infra/main/template.yaml
- yarn.lock
- Create new alarms for the account interventions queue
- Create parameters to share the queue names between the main and alarm stack
- Updated a dev dependency as there was a security notice
- So that we can monitor the status of account interventions, and be infomred when there is an issue
https://govukverify.atlassian.net/browse/OLH-2289
Verified that the alarms are created on dev, and that they go into alarm
> OLH-2289 Alarms for the Account Interventions Events Queue

- src/infra/alarm/template.yaml
- Change the TxMA latency alarm to the new TxMA Handler
The metric was checking the time for the InterventionHandler, we now use the TxMA handler, so we should change it. There were a lot of 2 second execution time alarms, which were triggering as a result.
https://govukverify.atlassian.net/browse/OLH-2291
> OLH-2291 update alarm

- package.json
- yarn.lock
BAU: Update Axios to v1.8.2 due to vulnerability 
https://github.com/axios/axios/issues/6463
> Update axios to v1.8.2

- .github/workflows/acceptance-checks.yaml
- .github/workflows/ensure-sha-pinned-actions.yaml
Set the GITHUB_TOKEN permissions to read only for the workflows which run the tests and check for pinned action versions.
If a workflow doesn't have any permissions defined it inherits from the repo permissions. Since this repo was created before Feb 2023, the default permissions are read/write.
These workflows don't need any write permissions so we can restrict them to the minimum for safety.
This PR fixes security alerts [1](https://github.com/govuk-one-login/account-interventions-service/security/code-scanning/1) & [2](https://github.com/govuk-one-login/account-interventions-service/security/code-scanning/2). 
If these two workflows still run and pass on this PR then this change is working.
> OLH-2619: Restrict actions workflows to repo read permissions
